CREATE TABLE "categorias" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "nome" varchar(50) NOT NULL,
                              "icone_nome" varchar(50),
                              "criado_em" timestamp with time zone DEFAULT (now())
);