CREATE TABLE "relatos" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "perfil_id" uuid NOT NULL,
                           "categoria_id" INTEGER NOT NULL,
                           "status" varchar(20) NOT NULL,
                           "descricao" text,
                           "url_foto" varchar(255),
                           "latitude" decimal(10,8) NOT NULL,
                           "longitude" decimal(11,8) NOT NULL,
                           "criado_em" timestamp with time zone DEFAULT (now()),

                           CONSTRAINT fk_relato_perfil
                               FOREIGN KEY ("perfil_id")
                                   REFERENCES "perfis" ("id")
                                   ON DELETE CASCADE,

                           CONSTRAINT fk_relato_categoria
                               FOREIGN KEY ("categoria_id")
                                   REFERENCES "categorias" ("id")
                                   ON DELETE CASCADE
);